//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations.Schema;

namespace Bearlog.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GenTree
    {
        [Column("id")]
        public int Id { get; set; }
        [Column("user_id")]
        public int UserId { get; set; }
        [Column("gentree_name")]
        public string GenTreeName { get; set; }
        [Column("gentree_json")]
        public string GenTreeJson { get; set; }
    
        public virtual User User { get; set; }
    }
}
