//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations.Schema;

namespace StridingSoft.Services
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [Column("id")]
        public int id { get; set; }
        [Column("user_name")]
        public string user_name { get; set; }
        [Column("password")]
        public string password { get; set; }
        [Column("email")]
        public string email { get; set; }
        [Column("registration_date")]
        public DateTime registration_date { get; set; }
        [Column("last_activity_date")]
        public DateTime? last_activity_date { get; set; }
    
        public virtual GenTree GenTree { get; set; }
    }
}
