//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StridingSoft.Services.Models.Collectioner
{
    using System;
    using System.Collections.Generic;
    
    public partial class section
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public section()
        {
            this.items = new HashSet<item>();
        }
    
        public int id { get; set; }
        public int collection_id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public System.DateTime created_date { get; set; }
        public int creator_id { get; set; }
    
        public virtual collection collection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<item> items { get; set; }
        public virtual user user { get; set; }
    }
}
